name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## OpenAI Java SDK v$RESOLVED_VERSION

  ### Maven Dependency
  
  ```xml
  <dependency>
      <groupId>io.github.twwch</groupId>
      <artifactId>markdwon2office</artifactId>
      <version>$RESOLVED_VERSION</version>
  </dependency>
  ```
  
  ### Gradle Dependency
  
  ```gradle
  implementation 'io.github.twwch:markdwon2office:$RESOLVED_VERSION'
  ```

  ## Changes

  $CHANGES
  
  ### Links
  
  - [Maven Central](https://central.sonatype.com/artifact/io.github.twwch/markdwon2office/$RESOLVED_VERSION)
  - [Documentation](https://github.com/twwch/markdwon2office/blob/main/README.md)